### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by orangeniux** [dotXem/GLYFE#1]
Really appretiate for your articles and code about the CGMs analysis, but here is an obstructive issue for doing reproduction experiments, as it's unavailable for me to access the Ohio dataset (I am already a master graduate). So whether there's possibility to share some examples of the ohio data which only show the format with no glucose value(that could be set as zero for desensitization)? thanks a lot.

**Comment by dotXem** [comment]
Thank you for the feedback. Unfortunately, I don't have access to this data anymore, so I won't be able to do so. Sorry for that.
